package org.learning.records;

public record Customer(long id, String name, String email) {

    @Override // Override accessor method generated by the compiler
    public String name() {
        return name != null && !name.isBlank() ? name : "anonymous";
    }

    // Rules:
    // - The return type of overridden accessor method must be the same as the type of the component
    // - Accessor method cannot have a 'throws' clause

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer customer = (Customer) o;
        return id == customer.id;
    }

    @Override
    public int hashCode() {
        return Long.hashCode(id);
    }


}
